from FetchPlayerAndGames import executeQueryGames
from FetchAchievements import executeFetchAchievements
from BuildMonthlyScoresToJSON import executeMonthlyScoresBuild
from BuildMonthlyStarQualityToJSON import executeBuildMonthlyStars
from BuildAchievementScoresToJSON import executeAchievementBuild
from BuildPlayerBlob import executeBuildPlayerBlobs
from BuildHeadToHeadsToJSON import buildHeadToHeads


executeMonthlyScoresBuild()
executeBuildMonthlyStars()
executeAchievementBuild()
executeBuildPlayerBlobs()
buildHeadToHeads()