USE [master]
GO

/****** Object:  Database [LaserScraper]    Script Date: 16-Aug-19 9:59:48 ******/
CREATE DATABASE [LaserScraper]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LaserScraper', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\LaserScraper.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LaserScraper_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\LaserScraper_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LaserScraper].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LaserScraper] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LaserScraper] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LaserScraper] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LaserScraper] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LaserScraper] SET ARITHABORT OFF 
GO

ALTER DATABASE [LaserScraper] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LaserScraper] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LaserScraper] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LaserScraper] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LaserScraper] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LaserScraper] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LaserScraper] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LaserScraper] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LaserScraper] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LaserScraper] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LaserScraper] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LaserScraper] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LaserScraper] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LaserScraper] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LaserScraper] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LaserScraper] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LaserScraper] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LaserScraper] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LaserScraper] SET  MULTI_USER 
GO

ALTER DATABASE [LaserScraper] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LaserScraper] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LaserScraper] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LaserScraper] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LaserScraper] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LaserScraper] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LaserScraper] SET  READ_WRITE 
GO


